"""empty message

Revision ID: 56c44128a2d8
Revises: 46f9ea96f1e4
Create Date: 2025-10-10 22:53:41.632365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c44128a2d8'
down_revision = '46f9ea96f1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narration', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['reference'])

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paystack_customer_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('paystack_dedicated_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('paystack_bank_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_column('paystack_bank_name')
        batch_op.drop_column('paystack_dedicated_account')
        batch_op.drop_column('paystack_customer_code')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('reference')
        batch_op.drop_column('narration')

    # ### end Alembic commands ###
